// Set variable for accepted color keywords for SVG
const colorArray = [
  "aliceblue",
  "antiquewhite",
  "aqua",
  "aquamarine",
  "azure",
  "beige",
  "bisque",
  "black",
  "blanchedalmond",
  "blue",
  "blueviolet",
  "brown",
  "burlywood",
  "cadetblue",
  "chartreuse",
  "chocolate",
  "coral",
  "cornflowerblue",
  "cornsilk",
  "crimson",
  "cyan",
  "darkblue",
  "darkcyan",
  "darkgoldenrod",
  "darkgray",
  "darkgreen",
  "darkgrey",
  "darkkhaki",
  "darkmagenta",
  "darkolivegreen",
  "darkorange",
  "darkorchid",
  "darkred",
  "darksalmon",
  "darkseagreen",
  "darkslateblue",
  "darkslategray",
  "darkslategrey",
  "darkturquoise",
  "darkviolet",
  "deeppink",
  "deepskyblue",
  "dimgray",
  "dimgrey",
  "dodgerblue",
  "firebrick",
  "floralwhite",
  "forestgreen",
  "fuchsia",
  "gainsboro",
  "ghostwhite",
  "gold",
  "goldenrod",
  "gray",
  "grey",
  "green",
  "greenyellow",
  "honeydew",
  "hotpink",
  "indianred",
  "indigo",
  "ivory",
  "khaki",
  "lavender",
  "lavenderblush",
  "lawngreen",
  "lemonchiffon",
  "lightblue",
  "lightcoral",
  "lightcyan",
  "lightgoldenrodyellow",
  "lightgray",
  "lightgreen",
  "lightgrey",
  "lightpink",
  "lightsalmon",
  "lightseagreen",
  "lightskyblue",
  "lightslategray",
  "lightslategrey",
  "lightsteelblue",
  "lightyellow",
  "lime",
  "limegreen",
  "linen",
  "magenta",
  "maroon",
  "mediumaquamarine",
  "mediumblue",
  "mediumorchid",
  "mediumpurple",
  "mediumseagreen",
  "mediumslateblue",
  "mediumspringgreen",
  "mediumturquoise",
  "mediumvioletred",
  "midnightblue",
  "mintcream",
  "mistyrose",
  "moccasin",
  "navajowhite",
  "navy",
  "oldlace",
  "olive",
  "olivedrab",
  "orange",
  "orangered",
  "orchid",
  "palegoldenrod",
  "palegreen",
  "paleturquoise",
  "palevioletred",
  "papayawhip",
  "peachpuff",
  "peru",
  "pink",
  "plum",
  "powderblue",
  "purple",
  "red",
  "rosybrown",
  "royalblue",
  "saddlebrown",
  "salmon",
  "sandybrown",
  "seagreen",
  "seashell",
  "sienna",
  "silver",
  "skyblue",
  "slateblue",
  "slategray",
  "slategrey",
  "snow",
  "springgreen",
  "steelblue",
  "tan",
  "teal",
  "thistle",
  "tomato",
  "turquoise",
  "violet",
  "wheat",
  "white",
  "whitesmoke",
  "yellow",
  "yellowgreen",
];

// Prompt questions for inquirer
const questions = [
  {
    type: 'input',
    name: 'text',
    message: 'Enter text for logo (up to 3 characters)',
    // Confirm input is less than 4 characters or display error message, if not
    validate(value) {
      if (value.length < 4) {
        return true
      } else {
        return 'Please shorten your entry. Only up to 3 characters is allowed.'
      };
    },
  },
  {
    type: 'input',
    name: 'textColor',
    message: 'Enter desired text color (color keyword or hexadecimal color code)',
    // Confirm the input is accepted color keyword or valid hexadecimal color code or display error message, if not
    validate(value) {
      const regex = new RegExp(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/);
      if (colorArray.includes(value.toLowerCase()) || regex.test(value)) {
        return true
      } else {
        return 'Please enter a valid color keyword or valid hexadecimal code. Accepted color keywords can be found here: https://www.w3.org/TR/SVG11/types.html#ColorKeywords'
      };
    },
  },
  {
    type: 'list',
    name: 'shape',
    message: 'Select a shape for the logo',
    choices: [
      'Circle',
      'Triangle',
      'Square',
    ],
  },
  {
    type: 'input',
    name: 'shapeColor',
    message: 'Enter desired shape color (color keyword or hexadecimal number)',
    // Confirm the input is accepted color keyword or valid hexadecimal color code and display error message, if not
    validate(value) {
      const regex = new RegExp(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/);
      if (colorArray.includes(value.toLowerCase()) || regex.test(value)) {
        return true
      } else {
        return 'Please enter a valid color keyword or valid hexadecimal code. Accepted color keywords can be found here: https://www.w3.org/TR/SVG11/types.html#ColorKeywords'
      };
    },
  },
];

// Export questions
module.exports = questions;